# Application name
spring.application.name=fraud-ai-assistant-service

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/frauddetectiondb
spring.datasource.username=postgres
spring.datasource.password=root

# JPA configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# AWS Bedrock region
spring.ai.bedrock.aws.region=us-east-1
#spring.ai.bedrock.cohere.embedding.model=cohere.embed-english-v3

spring.ai.bedrock.titan.embedding.enabled=false
spring.ai.bedrock.cohere.embedding.enabled=false



# Disable Cohere embedding (avoid duplicate embedding beans)


# Server port
server.port=8086

# Actuator endpoints
management.endpoints.web.exposure.include=health,info



# =========================
# Ollama Configuration
# =========================
spring.ai.ollama.base-url=http://localhost:11434

# embedding model
spring.ai.ollama.embedding.model=nomic-embed-text