spring.application.name=Fraud-Management


server.port=8082

logging.file.name=logs/application.log

logging.level.org.springframework=INFO
logging.level.com.fraud_detection=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=jdbc:postgresql://localhost:5432/frauddetectiondb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Kafka Consumer Configuration
kafka.bootstrap-servers=localhost:9092
#kafka.bootstrap-servers=localhost:9092
kafka.consumer.group-id=fraud-group
kafka.maxPollRecords = 1000
kafka.maxPollIntervals= 30000
kafka.sessionTimeout =6000000
kafka.concurrency=3
kafka.idleEventInterval=6000000

kafka.telemetry.enabled=false

kafka.consumer.auto-offset-reset=earliest
kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka Producer Configuration
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

logging.level.org.apache.kafka=DEBUG
logging.level.org.springframework.kafka=DEBUG


#auto.create.topics.enable=true